### ISSUE TITLE
Red Agent Making Illegal Moves

### ISSUE THREAD

**Issue by Dawn-RL** [microsoft/CyberBattleSim#54]
Hi,

Just double checking - there may be a small bug with the red agent choosing invalid actions from the action space. Repro can be found [here](https://github.com/Dawn-RL/CyberBattleSim-fork/tree/second_bug_branch) - second_bug_branch - with an example case shown in 'notebooks/Random_Network_Invalid_Move.ipynb'. 

Additional nodes are set up with create_node_data_two, such that the firewall conf is set to block all and there are no SMB / RDP vulns present. Only one edge is made for each new node, between the local machine that has the "knows_on_capture" exploit and the target node it pivots to. The idea is that once the knows_on_capture exploit is launched, essentially its like finding handwritten credentials, auto granting access to the remote machine. 

From the ipynb file we can see that there are many attempted remote connections between these additional nodes and the original nodes in the network. Edges are added with the EdgeAnnotation.REMOTE as it tries to exploit RDP / SMB connections which shouldn't be possible. The local vulnerability library of the new nodes are empty { }, firewall rules are set to block all and no edges were formed when generating the nx graph in edges_labels dict. 

The agent doesn't appear successful with its attacks, and if it helps I'm fairly confident that these attacks are only attempted at the very end of all its other potential attack routes, but I find it strange that it can try make these moves in the first place. This would add a +1 move which could skew results if the agent shouldn't be able to select from these moves to begin with. 

Not sure if related but could be due to the way we are calling __mark_node_as_owned directly? 

Thanks in advanced!

**Comment by blumu** [comment]
@Dawn-RL As you suggested I think it's due to the fact that you are calling `__mark_node_as_owner`. If I understand correctly the intent of the `LeakyGuyId` you are implementing it should only leak the existence of the node. If that's what you want to do then you can implement this by calling instead: `__mark_node_as_discovered`.

**Comment by Dawn-RL** [comment]
Hi Blumu,

Ideally we would like it to own the node automatically, so I think mark_node_as_owned should work. It just seems to me like the action mask is missing some verification when selecting from a pool of valid moves. 

Cheers

**Comment by blumu** [comment]
I see, so the vulnerability name `knows_on_capture` might have misled me due to the terminology used in our simulation (`known` for us means `discovered` as opposed to `owned`).

I looked at the notebook (Thanks for putting this together by the way!) and I notice that nodes 4, 6 and 14 all have the `knows_on_capture` vulnerability set to grant access to respectively nodes 15, 16, 17. 

![image](https://user-images.githubusercontent.com/3913258/172513852-5ffc2ca9-5cf7-4c72-9634-215419f71f1d.png)

Therefore, if the agent owns 4, 6 and 14 then it can exploits the `knows_on_capture` vulnerability to gain ownership of 15, 16 and 17 via the `LeakedGuyId` outcome of the vulnerability exploit. 
The index for this local vulnerability appears to be `3` and you can see in the trace that it's indeed being used to get access to nodes id 16 and 17:

- From node id 14 (with index 8) the agent exploits the vulnerability with index 3 to get ownership of node id 17:
```
+ rewarded action: {'local_vulnerability': array([8, 3], dtype=int32)} total_reward=359.0 reward=2.0 @t=617
```
![image](https://user-images.githubusercontent.com/3913258/172516060-6ad9f432-a633-4d5e-a291-7792a02ea680.png)

- Further down, from node id 6 (with index 12) the agent exploits the same `knows_on_capture` vulnerability (index 3) to own node id 16:
``` 
+ rewarded action: {'local_vulnerability': array([12,  3], dtype=int32)} total_reward=511.0 reward=2.0 @t=862
```
![image](https://user-images.githubusercontent.com/3913258/172516891-b6ff094f-daa7-496b-a48e-8bd6da440ba7.png)

So, it's expected to see some activity from node id 16 and 17.

Now according to the final table in your simulation, node 15 is never owned so I cannot explain why we see some activity from this node. There might indeed be a bug somewhere, I need to investigate further.

**Comment by blumu** [comment]
@Dawn-RL The main branch has some changes to avoid confusion between the node internal IDs and the node indices used by the agent. In particular when pretty printing the rewarded actions it now shows the actual node ID from the environment graph. It also prints the vulnerability name. I've rebased your branch on it and rerun your notebook: https://github.com/microsoft/CyberBattleSim/blob/wiblum/dawnrl/second_bug_branch/notebooks/Random_Network_Invalid_Move.ipynb
It's now easier to see steps where the agent exploits the `Knows_on_capture` vulnerability to access nodes with ID > 15. E.g., here node with ID 2 exploits the vulnerability to gain ownership of 15:
![image](https://user-images.githubusercontent.com/3913258/172665558-70865ae2-8eeb-4890-8354-bab2ae6284f3.png)

I was not able to reproduce the situation you described where you could see activity from a node that's not owned by the agent. Take a look and let me know if you still think there is a bug.
