### ISSUE TITLE
PrivilegeEscalation marks nodes as owned, but doesn't reward agent with node value

### ISSUE THREAD

**Issue by forrestmckee** [microsoft/CyberBattleSim#71]
Is it correct behavior to be able to "own" a node via `PrivilegeEscalation`, but not be rewarded for that node's value?
It [looks like](https://github.com/microsoft/CyberBattleSim/blob/main/cyberbattle/simulation/actions.py#L319) the node value is never added to the reward [unless](https://github.com/microsoft/CyberBattleSim/blob/main/cyberbattle/simulation/actions.py#L528) it was owned via `connect_to_remote_machine`

My use case is exploiting a remote vulnerability that yields Admin or System privilege. The node is marked as owned, but the agent doesn't receive the node value as a reward.

**Comment by forrestmckee** [comment]
I've created a quick [example](https://github.com/forrestmckee/CyberBattleSim/blob/privilege_escalation_example/notebooks/privilege_escalation_example.ipynb) that demonstrates what I'm talking about.

**Comment by blumu** [comment]
Thank you for sharing the repro! So that's indeed a bug. The code that's handling remote exploits does not include the value of the node in the returned reward, it only accounts for discovered nodes:

https://github.com/microsoft/CyberBattleSim/blob/41a57538120e9e1e54dcc84d6a458ae74af5d4ca/cyberbattle/simulation/actions.py#L353-L354

We should add the value of any owned node, just like we do for the `connect` action:

https://github.com/microsoft/CyberBattleSim/blob/41a57538120e9e1e54dcc84d6a458ae74af5d4ca/cyberbattle/simulation/actions.py#L528

**Comment by blumu** [comment]
@forrestmckee You can cherry pick the fix from this branch: 

https://github.com/microsoft/CyberBattleSim/tree/wiblum/71

It will need some more testing before merging into the `main` branch, but I've verified that it fixes the problem on your repro notebook. Let me know if that works for you.

**Comment by forrestmckee** [comment]
> @forrestmckee You can cherry pick the fix from this branch:
> 
> https://github.com/microsoft/CyberBattleSim/tree/wiblum/71
> 
> It will need some more testing before merging into the `main` branch, but I've verified that it fixes the problem on your repro notebook. Let me know if that works for you.

Sorry for the delay. 
Yes, this fixed the issue for me. Thanks!
